services:
  - type: web
    name: voteeq-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CORS_ORIGIN
        value: https://voteeq-roi-dev.vercel.app
      - key: JWT_SECRET
        generateValue: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
